# GET http://localhost:5001/api/v1/bank-account-lookup/by-balance?balance=100&equalityType=GREATER_THAN HTTP/1.1

GET http://localhost:5001/api/v1/bank-account-lookup/by-balance?balance=150&equalityType=LESS_THAN HTTP/1.1
